### ISSUE TITLE
Roadmap for PyCall 2.0

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/PyCall.jl#629]
Now that #517 is merged, there are a few things remaining to do before we try to move all PyCall users to the new interface.

First, we need to deprecate some more things (probably in a "1.9" release or similar) to help with the transition:

- [ ] `@pyimport` and `pywrap` — just do `pyimport` now
- [ ] `getindex(::PyObject, ::Integer)` and similar — these will stop subtracting 1 in PyCall 2.0, so they will have to be deprecated for now.

Some other things I would like to change during the big transition:

- [ ] Make automatic conversion more conservative about producing native Julia objects.  Convert Python lists to `PyVector`, dictionaries to `PyDict`, and NumPy arrays to `PyArray` by default, but don't convert subclasses of these?

**Comment by marius311** [comment]
Are we slated to lose `@pyimport numpy as np` type syntax? If so, I'd cast my vote against that, I find it quite logical to be able to mirror exact the Python importing syntax, and I'd bet it makes things for anyone coming from Python simpler too.

**Comment by tkf** [comment]
I think #599 is the ultimate way to make PyCall Pythonista-friendly.  If you know Python syntax, just `eval`/`exec` it.  If `py"..."` has a proper namespacing, it's PEP 20-compliant so no Pythonista would complain :)

**Comment by marius311** [comment]
Interesting, so eventually it would just be `py"import numpy as np"` and then you have access to `np` from Julia? That's pretty cool, I see no problem with that solution from a user perspective (all I'd ask is that `@pyimport` stays around until that's implemented).

**Comment by stevengj** [comment]
Yes, we are slated to lose `@pyimport numpy as np`.  You now do `np = pyimport("numpy")`.

The goal of PyCall is not to allow you to use Python *syntax* in Julia.

**Comment by tkf** [comment]
Also:

- [ ] Switch to `Compat.hasproperty` when https://github.com/JuliaLang/Compat.jl/pull/650 is merged.

**Comment by stevengj** [comment]
What I'd like to do now is to test some of the main PyCall-using packages like SymPy and PyPlot on PyCall `master` — they should continue to work, albeit with lots of deprecation messages.   Help with this would be appreciated.

**Comment by tkf** [comment]
By testing, you mean reverse-dependency tests like this https://github.com/JuliaPy/PyPlot.jl/pull/425?  Or just trying PyCall master in daily use?

**Comment by stevengj** [comment]
Reverse-dependency tests are fine.  PyPlot's test suite isn't very good, though, so it requires some manual playing around.

**Comment by tkf** [comment]
Now that #636 is fixed, are there other blockers for v1.19?

**Comment by stevengj** [comment]
No, I think we are ready for a new 1.x release.

**Comment by ararslan** [comment]
The `getindex(::PyObject, ::AbstractString)` deprecation introduced [two years ago](https://github.com/JuliaPy/PyCall.jl/pull/517) means that accessing values in Python `dict`s requires `d.__getitem__(k)` instead of `d[k]`. I'm assuming that the removal of that deprecation would permit using `d[k]` directly, which would be nice. Is there an expected timeline now for PyCall 2.0? Seems all but one of Steven's items in the issue body have been implemented.

**Comment by tkf** [comment]
Another thing we can do is to change the default build to use libpython shipped via the artifact system, even in Linux.  This might improve the experience of end-users who happen to use Python libraries as transitive dependencies.
